UnitOfWorkTrial/Models/Employee.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using UnitOfWorkTrial.Enums;

namespace UnitOfWorkTrial.Models
{
    public class Employee
    {
        //1. Setting Properties in Employee Model to create the database table using these entities. 
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public EGender Gender { get; set; }

        [Display(Name = "Department Name")]
        public int DepartmentId { get; set; }
        public Department? Department { get; set; }
    }
}

UnitOfWorkTrial/Models/ViewModels/EmployeeViewModel.cs
namespace UnitOfWorkTrial.Models.ViewModels
{
    public class EmployeeViewModel
    {
        public List<Employee> Employees { get; set; } = new List<Employee>();
        public string[] AppliedFilters { get; set; }
    }
}

UnitOfWorkTrial/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using UnitOfWorkTrial.Models;
using UnitOfWorkTrial.UOW;

namespace UnitOfWorkTrial.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public DepartmentsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> DepIndex()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DepIndex(Department department)
        {
            if (!String.IsNullOrEmpty(department.Name))
            {
                try
                {
                    _unitOfWork.CreateTransaction();

                    await _unitOfWork.Departments.InsertAsync(department);

                    await _unitOfWork.Save();

                    _unitOfWork.Commit();

                    return RedirectToAction("Index", "Employees");
                }
                catch (Exception)
                {
                    _unitOfWork.Rollback();
                }
            }
            return View(department);
        }
    }
}

UnitOfWorkTrial/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using UnitOfWorkTrial.Models;
using UnitOfWorkTrial.Models.Filters;
using UnitOfWorkTrial.Models.ViewModels;
using UnitOfWorkTrial.UOW;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace UnitOfWorkTrial.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public EmployeesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //Get Employees
        //[AllowAnonymous]
        [AuthorizationExceptionFilter]      //Custom Exception Filter
        [ResponseCacheAttribute(NoStore = true, Duration = 10)]     //Result Filter
        [CustomAuthorizationFilter]        //Action Filter
        public async Task<IActionResult> Index(Employee employee, int[] DepId, string searchText = "", int page = 1, int size = 10)
        {
            if(HttpContext.Session.GetString("UserSession") != null)
            {
                ViewBag.Session = HttpContext.Session.GetString("UserSession");
            }
            else
            {
                return RedirectToAction("Login", "Users");
            }

            

            string ArrayString = String.Join(",", DepId);

            int recsCount = await _unitOfWork.Employees.GetAllEmployeesCountAsync(searchText, DepId);
            if (recsCount <= (page - 1) * size)
            {
                page = 1;
            }

            var sp = await _unitOfWork.Employees.GetEmployeeDataStoredProcedure(page, size, searchText, ArrayString);

            int totalPages = (int)Math.Ceiling((decimal)recsCount / (decimal)size);
            int currentPage = page;
            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if (startPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }
            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }


            ViewBag.CurrentPage = currentPage;
            ViewBag.TotalPages = totalPages;
            ViewBag.StartPage = startPage;
            ViewBag.EndPage = endPage;
            ViewBag.SearchText = searchText;
            ViewData["DepartmentId"] = new SelectList(await _unitOfWork.Departments.GetAllAsync(), "DepartmentId", "Name");
            ViewBag.DepId = DepId;
            ViewBag.ArrayString = ArrayString;
            var SearchTextLength = !string.IsNullOrEmpty(searchText) ? 1 : 0;
            string[] AppliedFilters = new string[DepId.Length + SearchTextLength];


            if (!string.IsNullOrEmpty(searchText))
            {
                AppliedFilters[0] = searchText;
            }



            if (DepId.Length > 0)
            {
                var start = !string.IsNullOrEmpty(searchText) ? 1 : 0;
                foreach (var item in DepId)
                {
                    var departmentIdAsString = item.ToString();
                    var departmentName = ((SelectList)ViewData["DepartmentId"]).FirstOrDefault(d => d.Value == departmentIdAsString)?.Text;
                    if (!string.IsNullOrEmpty(departmentName))
                    {
                        AppliedFilters[start] = departmentName;
                    }
                    start++;
                }

            }

            ViewBag.Data = sp;
            var result = new EmployeeViewModel()
            {
                Employees = sp,
                AppliedFilters = AppliedFilters
            };
            return View(result);

        }

        //[Authorize]
        //Get Employees/Details
        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            //Using Employee Repository to Fetching Employee along with thier Department Data by Employee Id
            var employee = await _unitOfWork.Employees.GetEmployeeByIdAsync(Convert.ToInt32(Id));
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        //Get Employees/Create
        public async Task<IActionResult> Create()
        {
            ViewData["DepartmentId"] = new SelectList(await _unitOfWork.Departments.GetAllAsync(), "DepartmentId", "Name");
            return View();
        }

        //Post Employees/Create
        [HttpPost]
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [ValidateAntiForgeryToken]      //Action Filter
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.CreateTransaction();

                    await _unitOfWork.Employees.InsertAsync(employee);

                    await _unitOfWork.Save();

                    _unitOfWork.Commit();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    _unitOfWork.Rollback();
                }
            }
            ViewData["DepartmentId"] = new SelectList(await _unitOfWork.Departments.GetAllAsync(), "DepartmentId", "Name", employee.Department);
            return View(employee);
        }

        //Get Employees/Edit
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var employee = await _unitOfWork.Employees.GetEmployeeByIdAsync(Convert.ToInt32(Id));

            if (employee == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(await _unitOfWork.Departments.GetAllAsync(), "DepartmentId", "Name", employee.DepartmentId);
            return View(employee);
        }

        //Post Employees/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, Employee employee)
        {
            if (Id != employee.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.CreateTransaction();

                    await _unitOfWork.Employees.UpdateAsync(employee);

                    await _unitOfWork.Save();

                    _unitOfWork.Commit();

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    _unitOfWork.Rollback();
                }
            }

            ViewData["DepartmentId"] = new SelectList(await _unitOfWork.Departments.GetAllAsync(), "DepartmentId", "Name", employee.DepartmentId);
            return View(employee);
        }
        // GET: Employees/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //Use Employee Repository to Fetch Employees along with the Department Data by Employee Id
            var employee = await _unitOfWork.Employees.GetEmployeeByIdAsync(Convert.ToInt32(id));
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }
        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //Begin The Transaction
            _unitOfWork.CreateTransaction();
            var employee = await _unitOfWork.Employees.GetByIdAsync(id);
            if (employee != null)
            {
                try
                {
                    await _unitOfWork.Employees.DeleteAsync(id);
                    //Save Changes to database
                    await _unitOfWork.Save();
                    //Commit the Changes to database
                    _unitOfWork.Commit();
                }
                catch (Exception)
                {
                    //Rollback Transaction
                    _unitOfWork.Rollback();
                }
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

UnitOfWorkTrial/Views/Employees/Create.cshtml
@model UnitOfWorkTrial.Models.Employee
@using UnitOfWorkTrial.Enums

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId">
                    <option>
                        Select Department
                    </option>
                </select>
            </div> 
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                @Html.DropDownList("Gender",
                         Html.GetEnumSelectList<EGender>(),
                         "Select Gender",
                         new { @class = "form-control" }
                         )
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

UnitOfWorkTrial/Views/Employees/Delete.cshtml
@model UnitOfWorkTrial.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

UnitOfWorkTrial/Views/Employees/Details.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor accessor;
@model UnitOfWorkTrial.Models.Employee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<h4>@accessor.HttpContext.Session.GetString("Key")</h4>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd> 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.Name)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

UnitOfWorkTrial/Views/Employees/Edit.cshtml
@model UnitOfWorkTrial.Models.Employee
@using UnitOfWorkTrial.Enums

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                @Html.DropDownList("Gender",
                         Html.GetEnumSelectList<EGender>(),
                         "Select Gender",
                         new { @class = "form-control" }
                         )
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UnitOfWorkTrial/Views/Employees/Index.cshtml
@using UnitOfWorkTrial.Enums
@using UnitOfWorkTrial.Models.ViewModels
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@model EmployeeViewModel

@{
    ViewData["Title"] = "Index";
    var appliedFiltersJson = Newtonsoft.Json.JsonConvert.SerializeObject(Model.AppliedFilters);
}

@Html.Hidden("appliedFiltersJson", appliedFiltersJson)


<div class="hstack gap-3 align-items float-end">
    <span>Welcome @ViewBag.Session</span>
    <span>
        <b>Name:</b> @HttpContextAccessor?.HttpContext?.Request.Cookies["Name"]
        <br />
    </span>
    <form asp-controller="Users" asp-action="Logout">
        <button type="submit" class="btn btn-danger position-relative">Logout</button>
    </form>
</div>
<br />

<div class="container d-flex justify-content-center align-items-center">
    <div class="row">
        <div class="col text-center">
            <h1>Employee Database</h1>
        </div>
    </div>
</div>

<div class="hstack gap-3">
    @* Modal Button *@
    <div>
        <button type="button" class="btn btn-secondary filter-button" data-toggle="modal" data-target="#Filter-Container">
            Filter Employees
        </button>
    </div>

    @* Modal *@

    <div class="modal fade" id="Filter-Container" ; tabindex="-1" role="dialog" aria-labelledby="Filter-ContainerLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="Filter-ContainerLabel">Filter Employees</h5>
                    <button type="button" class="close border" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form asp-asp-controller="Employees" asp-action="Index" method="get">
                        <div class="hstack gap-4">
                            <div class="btn-group">
                                <input class="form-control me-auto" type="text" name="searchText" value="@ViewBag.SearchText" placeholder="Search Employee" />
                            </div>
                            <div>
                                <select class="form-control" id="Department" name="DepId" multiple>
                                    @foreach (var dep in ((SelectList)ViewData["DepartmentId"]).Items)
                                    {
                                        string str = @ViewBag.ArrayString;
                                        var cast = (Department)dep;
                                        if (str.Split(',').Contains(cast.DepartmentId.ToString()))
                                        {
                                            <option class="z-index-100 position-relative" value="@cast.DepartmentId" selected>@cast.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@cast.DepartmentId">@cast.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <br />
                        <div class="modal-footer justify-content-center">
                            <input class="btn btn-outline-primary" type="submit" value="Search" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <div class="vstack gap-3" align="right">
        <form asp-action="Create">
            <button type="submit" class="btn btn-dark position-relative">Add New Employee</button>
        </form>
    </div>
    <div align="right">
        <form asp-controller="Departments" asp-action="DepIndex">
            <button type="submit" class="btn btn-info position-relative">Add New Department</button>
        </form>
    </div>
</div>

<div><br /></div>


<div class="hstack gap-1">
    @foreach (var filter in Model.AppliedFilters)
    {
        <div class="hstack bubble">
            <button class="bubble-text">@filter</button>
            <button type="button" class="bubble-remove" aria-label="Close" onclick="RemoveBubble('@filter');">&times;</button>
        </div>
    }
</div>
<br />

<partial name="_EmployeeList" />

@*  @Html.Partial("_EmployeeList", Model)
 *@


<partial name="_Pagination" />


<script>
    $(Document).ready(function () {
        $('#Department').select2({
            placeholder: 'Select Departments',
            allowClear: true,
            tags: true // With this, you can add data that are not in the select options
        });
    });

</script>

<script>
    function SetDepartment(Page, SearchText) {
        // debugger
        var path = "/Employees/Index?Page=" + Page;
        if (SearchText != null && SearchText != '') {
            path += "&SearchText=" + SearchText;
        }

        var a = [@ViewBag.ArrayString];

        if (a.length > 0) {
            debugger
            $.each(a, function (index, value) {
                path += "&DepId=" + value;
            })
        }
        var hostname = window.location.origin;
        window.location.href = hostname + path;
    };
</script>


<script>
    // debugger
    $(document).on('click', '.filter-button', function () {
        $('#Filter-Container').modal('show');
    });
</script>

<script>
    $(document).on('click', '.select2-selection', function () {
        $('#Filter-Container').css('z-index', '0')
    });
</script>

@* <script>
    $(document).on('click', '.select2-container', function () {
        $('#Filter-Container').css('z-index', '0')
    });
</script> *@


<script>
    $(document).ready(function () {
        $(document).hover(function (event) {
            // Check if the clicked element is not within #Filter-Container
            if (!$(event.target).closest('#Filter-Container').length) {
                $('#Filter-Container').css('z-index', '1055');
            }
        });

        $(document).on('click', '.select2-selection', function () {
            $('#Filter-Container').css('z-index', '0');
        });
    });
</script>



<script>
    function RemoveBubble(filter) {
        debugger
        $(event.target).closest('.bubble').remove();
        var url = window.location.href;
        var urlParts = url.split('?');
        var baseUrl = urlParts[0];
        var searchParams = new URLSearchParams(urlParts[1]);

        var depIds = searchParams.getAll('DepId');
        if (depIds) {
            depIds = depIds.filter(depId => depId !== filter);
            searchParams.delete('DepId');
        }

        var searchText = searchParams.get('searchText');
        if (searchText && searchText.includes(filter)) {
            searchText = searchText.replace(filter, '').replace('&&', '&').replace('?&', '?');
            if (searchText === '') {
                searchParams.delete('searchText');
            } else {
                searchParams.set('searchText', searchText);
            }
        }

        // Construct the new URL
        var newUrl = baseUrl + '?' + searchParams.toString();

        // Redirect to the updated URL
        window.location.href = newUrl;
    }
</script>

UnitOfWorkTrial/Views/Employees/Login.cshtml
@model UnitOfWorkTrial.Models.User
@using UnitOfWorkTrial.Enums

@{
    ViewData["Title"] = "Login";
}

<h1>User Login</h1>

<hr />

@if(ViewBag.Message != null){
    <p style="color: red">@ViewBag.Message</p>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}